package atlas.java.sql;
public abstract interface CallableStatement extends atlas.java.sql.PreparedStatement {
	public abstract java.lang.String getString(java.lang.String p0);
	public abstract java.lang.String getString(int p0);
	public abstract void setTime(java.lang.String p0, java.sql.Time p1, java.util.Calendar p2);
	public abstract void setTime(java.lang.String p0, java.sql.Time p1);
	public abstract java.sql.Time getTime(int p0, java.util.Calendar p1);
	public abstract java.sql.Time getTime(java.lang.String p0);
	public abstract java.sql.Time getTime(int p0);
	public abstract java.sql.Time getTime(java.lang.String p0, java.util.Calendar p1);
	public abstract void setDate(java.lang.String p0, java.sql.Date p1, java.util.Calendar p2);
	public abstract void setDate(java.lang.String p0, java.sql.Date p1);
	public abstract java.math.BigDecimal getBigDecimal(java.lang.String p0);
	public abstract java.math.BigDecimal getBigDecimal(int p0);
	public abstract java.math.BigDecimal getBigDecimal(int p0, int p1);
	public abstract void setObject(java.lang.String p0, java.lang.Object p1);
	public abstract void setObject(java.lang.String p0, java.lang.Object p1, int p2);
	public abstract void setObject(java.lang.String p0, java.lang.Object p1, int p2, int p3);
	public abstract java.sql.Timestamp getTimestamp(java.lang.String p0, java.util.Calendar p1);
	public abstract java.sql.Timestamp getTimestamp(int p0, java.util.Calendar p1);
	public abstract java.sql.Timestamp getTimestamp(java.lang.String p0);
	public abstract java.sql.Timestamp getTimestamp(int p0);
	public abstract java.sql.Date getDate(java.lang.String p0);
	public abstract java.sql.Date getDate(int p0);
	public abstract java.sql.Date getDate(java.lang.String p0, java.util.Calendar p1);
	public abstract java.sql.Date getDate(int p0, java.util.Calendar p1);
	public abstract boolean wasNull();
	public abstract java.sql.Blob getBlob(java.lang.String p0);
	public abstract java.sql.Blob getBlob(int p0);
	public abstract java.sql.Clob getClob(java.lang.String p0);
	public abstract java.sql.Clob getClob(int p0);
	public abstract java.sql.RowId getRowId(int p0);
	public abstract java.sql.RowId getRowId(java.lang.String p0);
	public abstract java.sql.NClob getNClob(java.lang.String p0);
	public abstract java.sql.NClob getNClob(int p0);
	public abstract java.sql.SQLXML getSQLXML(int p0);
	public abstract java.sql.SQLXML getSQLXML(java.lang.String p0);
	public abstract java.lang.String getNString(int p0);
	public abstract java.lang.String getNString(java.lang.String p0);
	public abstract java.io.Reader getNCharacterStream(int p0);
	public abstract java.io.Reader getNCharacterStream(java.lang.String p0);
	public abstract void setBytes(java.lang.String p0, byte[] p1);
	public abstract void setBinaryStream(java.lang.String p0, java.io.InputStream p1);
	public abstract void setBinaryStream(java.lang.String p0, java.io.InputStream p1, int p2);
	public abstract void setBinaryStream(java.lang.String p0, java.io.InputStream p1, long p2);
	public abstract void registerOutParameter(int p0, int p1, int p2);
	public abstract void registerOutParameter(java.lang.String p0, int p1, int p2);
	public abstract void registerOutParameter(int p0, int p1, java.lang.String p2);
	public abstract void registerOutParameter(java.lang.String p0, int p1);
	public abstract void registerOutParameter(java.lang.String p0, int p1, java.lang.String p2);
	public abstract void registerOutParameter(int p0, int p1);
	public abstract void setNull(java.lang.String p0, int p1);
	public abstract void setNull(java.lang.String p0, int p1, java.lang.String p2);
	public abstract void setBigDecimal(java.lang.String p0, java.math.BigDecimal p1);
	public abstract void setString(java.lang.String p0, java.lang.String p1);
	public abstract void setAsciiStream(java.lang.String p0, java.io.InputStream p1);
	public abstract void setAsciiStream(java.lang.String p0, java.io.InputStream p1, long p2);
	public abstract void setAsciiStream(java.lang.String p0, java.io.InputStream p1, int p2);
	public abstract void setRowId(java.lang.String p0, java.sql.RowId p1);
	public abstract void setNString(java.lang.String p0, java.lang.String p1);
	public abstract void setNCharacterStream(java.lang.String p0, java.io.Reader p1, long p2);
	public abstract void setNCharacterStream(java.lang.String p0, java.io.Reader p1);
	public abstract void setNClob(java.lang.String p0, java.sql.NClob p1);
	public abstract void setNClob(java.lang.String p0, java.io.Reader p1, long p2);
	public abstract void setNClob(java.lang.String p0, java.io.Reader p1);
	public abstract void setClob(java.lang.String p0, java.io.Reader p1, long p2);
	public abstract void setClob(java.lang.String p0, java.io.Reader p1);
	public abstract void setClob(java.lang.String p0, java.sql.Clob p1);
	public abstract void setBlob(java.lang.String p0, java.io.InputStream p1, long p2);
	public abstract void setBlob(java.lang.String p0, java.sql.Blob p1);
	public abstract void setBlob(java.lang.String p0, java.io.InputStream p1);
	public abstract void setSQLXML(java.lang.String p0, java.sql.SQLXML p1);
	public abstract void setCharacterStream(java.lang.String p0, java.io.Reader p1, long p2);
	public abstract void setCharacterStream(java.lang.String p0, java.io.Reader p1, int p2);
	public abstract void setCharacterStream(java.lang.String p0, java.io.Reader p1);
	public abstract java.io.Reader getCharacterStream(java.lang.String p0);
	public abstract java.io.Reader getCharacterStream(int p0);
	public abstract void setURL(java.lang.String p0, java.net.URL p1);
	public abstract java.lang.Object getObject(java.lang.String p0, atlas.java.util.Map<java.lang.String, java.lang.Class<?>> p1);
	public abstract <T> T getObject(java.lang.String p0, java.lang.Class<T> p1);
	public abstract java.lang.Object getObject(int p0);
	public abstract java.lang.Object getObject(java.lang.String p0);
	public abstract <T> T getObject(int p0, java.lang.Class<T> p1);
	public abstract java.lang.Object getObject(int p0, atlas.java.util.Map<java.lang.String, java.lang.Class<?>> p1);
	public abstract boolean getBoolean(int p0);
	public abstract boolean getBoolean(java.lang.String p0);
	public abstract byte getByte(java.lang.String p0);
	public abstract byte getByte(int p0);
	public abstract short getShort(java.lang.String p0);
	public abstract short getShort(int p0);
	public abstract int getInt(int p0);
	public abstract int getInt(java.lang.String p0);
	public abstract long getLong(int p0);
	public abstract long getLong(java.lang.String p0);
	public abstract float getFloat(int p0);
	public abstract float getFloat(java.lang.String p0);
	public abstract double getDouble(java.lang.String p0);
	public abstract double getDouble(int p0);
	public abstract byte[] getBytes(int p0);
	public abstract byte[] getBytes(java.lang.String p0);
	public abstract java.sql.Array getArray(int p0);
	public abstract java.sql.Array getArray(java.lang.String p0);
	public abstract java.net.URL getURL(int p0);
	public abstract java.net.URL getURL(java.lang.String p0);
	public abstract void setBoolean(java.lang.String p0, boolean p1);
	public abstract void setByte(java.lang.String p0, byte p1);
	public abstract void setShort(java.lang.String p0, short p1);
	public abstract void setInt(java.lang.String p0, int p1);
	public abstract void setLong(java.lang.String p0, long p1);
	public abstract void setFloat(java.lang.String p0, float p1);
	public abstract void setDouble(java.lang.String p0, double p1);
	public abstract java.sql.Ref getRef(java.lang.String p0);
	public abstract java.sql.Ref getRef(int p0);
	public abstract void setTimestamp(java.lang.String p0, java.sql.Timestamp p1, java.util.Calendar p2);
	public abstract void setTimestamp(java.lang.String p0, java.sql.Timestamp p1);
}
