package atlas.java.sql;
public abstract interface PreparedStatement extends atlas.java.sql.Statement {
	public abstract void setRef(int p0, java.sql.Ref p1);
	public abstract void setArray(int p0, java.sql.Array p1);
	public abstract void setTime(int p0, java.sql.Time p1);
	public abstract void setTime(int p0, java.sql.Time p1, java.util.Calendar p2);
	public abstract void setDate(int p0, java.sql.Date p1);
	public abstract void setDate(int p0, java.sql.Date p1, java.util.Calendar p2);
	public abstract void clearParameters();
	public abstract void setObject(int p0, java.lang.Object p1, int p2);
	public abstract void setObject(int p0, java.lang.Object p1);
	public abstract void setObject(int p0, java.lang.Object p1, int p2, int p3);
	public abstract java.sql.ResultSetMetaData getMetaData();
	public abstract void setBytes(int p0, byte[] p1);
	public abstract void setBinaryStream(int p0, java.io.InputStream p1);
	public abstract void setBinaryStream(int p0, java.io.InputStream p1, long p2);
	public abstract void setBinaryStream(int p0, java.io.InputStream p1, int p2);
	public abstract void setNull(int p0, int p1, java.lang.String p2);
	public abstract void setNull(int p0, int p1);
	public abstract void setBigDecimal(int p0, java.math.BigDecimal p1);
	public abstract void setString(int p0, java.lang.String p1);
	public abstract void setAsciiStream(int p0, java.io.InputStream p1, int p2);
	public abstract void setAsciiStream(int p0, java.io.InputStream p1);
	public abstract void setAsciiStream(int p0, java.io.InputStream p1, long p2);
	public abstract void setRowId(int p0, java.sql.RowId p1);
	public abstract void setNString(int p0, java.lang.String p1);
	public abstract void setNCharacterStream(int p0, java.io.Reader p1);
	public abstract void setNCharacterStream(int p0, java.io.Reader p1, long p2);
	public abstract void setNClob(int p0, java.io.Reader p1, long p2);
	public abstract void setNClob(int p0, java.io.Reader p1);
	public abstract void setNClob(int p0, java.sql.NClob p1);
	public abstract void setClob(int p0, java.io.Reader p1);
	public abstract void setClob(int p0, java.io.Reader p1, long p2);
	public abstract void setClob(int p0, java.sql.Clob p1);
	public abstract void setBlob(int p0, java.sql.Blob p1);
	public abstract void setBlob(int p0, java.io.InputStream p1, long p2);
	public abstract void setBlob(int p0, java.io.InputStream p1);
	public abstract void setSQLXML(int p0, java.sql.SQLXML p1);
	public abstract java.sql.ResultSet executeQuery();
	public abstract int executeUpdate();
	public abstract void setUnicodeStream(int p0, java.io.InputStream p1, int p2);
	public abstract void addBatch();
	public abstract java.sql.ParameterMetaData getParameterMetaData();
	public abstract void setCharacterStream(int p0, java.io.Reader p1);
	public abstract void setCharacterStream(int p0, java.io.Reader p1, int p2);
	public abstract void setCharacterStream(int p0, java.io.Reader p1, long p2);
	public abstract void setURL(int p0, java.net.URL p1);
	public abstract boolean execute();
	public abstract void setBoolean(int p0, boolean p1);
	public abstract void setByte(int p0, byte p1);
	public abstract void setShort(int p0, short p1);
	public abstract void setInt(int p0, int p1);
	public abstract void setLong(int p0, long p1);
	public abstract void setFloat(int p0, float p1);
	public abstract void setDouble(int p0, double p1);
	public abstract void setTimestamp(int p0, java.sql.Timestamp p1);
	public abstract void setTimestamp(int p0, java.sql.Timestamp p1, java.util.Calendar p2);
}
